version: "3.4"

services:
    client:
        build:
          context: .
        environment:
            - HOST=0.0.0.0
            - PORT=5000
            - VITE_SIGNALING_SERVER=ws://127.0.0.1:5000
        volumes:
            - ./dist:/app/dist