version: "3.4"

services:
    backend:
        image: file-share/server:latest
        build:
          context: .
          target: prod
        ports:
          - 5000:5000
        environment:
            - HOST=0.0.0.0
            - PORT=5000
